### ISSUE TITLE
Archive / Delete this repo

### ISSUE THREAD

**Issue by duncdrum** [readchina/scb-hugo2#2]
This repo can be deleted and the webpage disabled. 

The only place that saw the old URL should be the readers of the draft chapter of the edited volume. 

We could try to establish a forwarder from the old URL or archive this and place a notice on the readme. I ll leave this up to you @whalekeykeeper , 

TLDR: this was a temporary repo, we need to do housekeeping

**Comment by whalekeykeeper** [comment]
The webpage is disabled.
There is a ReadMe file for this repo to direct people who are interested in Shouchaoben to the new webpage.
This repo will be archived in a few minutes.
